//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("API.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1;Instalador
        ///2;Adminsitrador
        ///3;Operador
        ///4;Lector básico
        ///5;Lector avanzado.
        /// </summary>
        internal static string datos_de_perfiles {
            get {
                return ResourceManager.GetString("datos_de_perfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1;8
        ///1;16
        ///2;7
        ///2;9
        ///2;11
        ///2;12
        ///2;8
        ///2;1
        ///2;4
        ///2;10.
        /// </summary>
        internal static string datos_de_perfiles_funciones {
            get {
                return ResourceManager.GetString("datos_de_perfiles_funciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usuario1;password1;nombre1;apellido1;email1;planta1;ubicación física1;departamento1;cargo1 
        ///usuario2;password2;nombre2;apellido2;email2;planta2;ubicación física2;departamento2;cargo2  
        ///usuario3;password3;nombre3;apellido3;email3;planta3;ubicación física3;departamento3;cargo3 
        ///usuario4;password4;nombre4;apellido4;email4;planta4;ubicación física4;departamento4;cargo4  
        ///usuario5;password5;nombre5;apellido5;email5;planta5;ubicación física5;departamento5;cargo5 .
        /// </summary>
        internal static string datos_de_usuarios {
            get {
                return ResourceManager.GetString("datos_de_usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usuario1;1
        ///usuario2;2
        ///usuario3;3
        ///usuario4;4
        ///usuario5;5.
        /// </summary>
        internal static string datos_de_usuarios_perfiles {
            get {
                return ResourceManager.GetString("datos_de_usuarios_perfiles", resourceCulture);
            }
        }
    }
}
